[build]
  command = "rm -rf node_modules package-lock.json .next && npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
